name: "CI Tests"

on:
    pull_request: null
    push:
        branches:
            - "*.x"

jobs:
    tests:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.can-fail }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    # Lowest Deps
                    - php: 7.1
                      symfony: 4.4.*
                      composer-flags: '--prefer-stable --prefer-lowest'
                      can-fail: false
                    # LTS with latest stable PHP
                    - php: 8.1
                      symfony: 5.4.*
                      composer-flags: '--prefer-stable'
                      can-fail: false
                    # Stable Symfony branches
                    - php: 7.4
                      symfony: 4.4.*
                      composer-flags: '--prefer-stable'
                      can-fail: false
                    - php: 8.0
                      symfony: 6.0.*
                      composer-flags: '--prefer-stable'
                      can-fail: false
                    # Development Symfony branches
                    - php: 8.1
                      symfony: 6.1.*@dev
                      composer-flags: ''
                      can-fail: false

        name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Cache Composer packages"
              uses: "actions/cache@v2"
              with:
                  path: "~/.composer/cache"
                  key: "php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}"
                  restore-keys: "php-"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php }}"
                  tools: "composer:v2,flex"

            - name: "Set Composer stability"
              if: "matrix.symfony == '6.1.*@dev'"
              run: "composer config minimum-stability dev"

            - name: "Remove symfony/security-guard"
              if: "matrix.symfony == '6.0.*' || matrix.symfony == '6.1.*@dev'"
              run: "composer remove --dev --no-update symfony/security-guard"

            - name: "Install dependencies"
              run: "composer update ${{ matrix.composer-flags }} --prefer-dist"
              env:
                SYMFONY_REQUIRE: "${{ matrix.symfony }}"

            - name: "Run PHPUnit Tests"
              run: make tests
