name: "CI Tests (for Web Token support only)"

on:
    pull_request:
    push:

jobs:
    tests:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.can-fail }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    # Lowest deps
                    - php: 8.2
                      symfony: 6.4.*
                      can-fail: false
                    # LTS with last stable PHP
                    - php: 8.3
                      symfony: 6.4.*
                      can-fail: false
                      # Stable Symfony branches
                    - php: 8.3
                      symfony: 7.0.*
                      can-fail: false

        name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 2

            - name: "Cache Composer packages"
              uses: "actions/cache@v3"
              with:
                  path: "~/.composer/cache"
                  key: "php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}"
                  restore-keys: "php-"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php }}"
                  tools: "composer:v2,flex"

            - name: "Require web-token/*"
              run: |
                composer require --dev --no-update web-token/jwt-bundle:"^3.0.6"
                composer require --dev --no-update web-token/jwt-checker:"^3.0.6"
                composer require --dev --no-update web-token/jwt-key-mgmt:"^3.0.6"
                composer require --dev --no-update web-token/jwt-signature-algorithm-hmac:"^3.0.6"
                composer require --dev --no-update web-token/jwt-encryption-algorithm-aesgcm:"^3.0.6"
                composer require --dev --no-update web-token/jwt-encryption-algorithm-aesgcmkw:"^3.0.6"

            - name: "Install dependencies"
              run: "composer update ${{ matrix.composer-flags }} --prefer-dist --prefer-stable"
              env:
                SYMFONY_REQUIRE: "${{ matrix.symfony }}"

            - name: "Run PHPUnit Tests"
              run: "vendor/bin/simple-phpunit --group web-token"
